site_name: PrivacyCredentials
site_url: https://example.com/

theme:
  name: material
  palette:
    scheme: normal
    primary: indigo
    accent: indigo
  logo: assets/logo.png
  font: false

  features:
    - navigation.sections
    - navigation.expand

repo_url: https://github.com/hesusruiz/PrivacyCredentials


markdown_extensions:
  - def_list
  - pymdownx.highlight
  - pymdownx.superfences
  - attr_list
  - admonition

plugins:
  - search
  - img2fig
  - render_swagger
  - kroki:
  - print-site:
      add_to_navigation: true
      print_page_title: 'Print Site'
      # Table of contents
      add_table_of_contents: true
      toc_title: 'Table of Contents'
      toc_depth: 6
      # Content-related
      add_full_urls: false
      enumerate_headings: true
      enumerate_figures: true
      add_cover_page: true
      cover_page_template: ""
      path_to_pdf: ""
      exclude:


extra_css:
  - stylesheets/extra.css


nav:
    - Introduction: 'index.md'
    - Architecture:
      - Overview: architecture/ar-overview.md
      - Relationship with EU COVID: architecture/relationship-with-eucovid.md
    - DID Methods:
        - ELSI: 'didmethods/elsi.md'
    - Credentials:
        - EU COVID: 'credentials/eu-covid.md'
        - W3C VC: 'credentials/w3c.md'
    - Trust Framework:
        - Overview: trustframework/tf-overview.md
        - Smart Contracts: trustframework/smart-contracts.md