
# Project information
site_name: PrivacyCredentials
site_url: https://hesusruiz.github.io/PrivacyCredentials/
site_author: Jesus Ruiz
site_description: >-
  PrivacyCredentials is a generic credential system which is designed to be secure, privacy-preserving, scalable, performant and robust. It is designed specifically for some important use cases where physical, on-person verification of identity of holder is needed and where normal W3C Verifiable Credential flows are not fully suitable as they are normally designed currently.

# Repository
repo_name: hesusruiz/PrivacyCredentials
repo_url: https://github.com/hesusruiz/PrivacyCredentials
edit_uri: ""

# Copyright
copyright: ''


theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: normal
    primary: indigo
    accent: indigo
  logo: assets/logo.png
#  font: false

  features:
    - navigation.sections
    - navigation.expand

use_directory_urls: false

markdown_extensions:
  - def_list
  - pymdownx.highlight
  - pymdownx.superfences
  - attr_list
  - admonition
  - toc


plugins:
  - search
  - img2fig
  - render_swagger
  - kroki:
  - print-site:
      add_to_navigation: true
      print_page_title: 'Print'
      # Table of contents
      add_table_of_contents: true
      toc_title: 'Table of Contents'
      toc_depth: 6
      # Content-related
      add_full_urls: false
      enumerate_headings: false
      enumerate_figures: true
      add_cover_page: true
      cover_page_template: ""
      path_to_pdf: ""
      exclude:


extra_css:
  - stylesheets/extra.css


nav:
    - Abstract: 'index.md'
    - Inroduction:
      - Features: 'features/features.md'
      - Architecture: 'architecture/privacy-architecture.md'
    - HCERTX:
      - Overview: 'hcertx/overview.md'
      - EU DCC container: 'hcertx/containerformat.md'
      - EU DCC v1 data model: 'hcertx/datamodel.md'
      - Trusted Lists: 'hcertx/trustedlists.md'
      - Security: 'hcertx/security-considerations.md'
    - W3C Credentials:
      - Data model: 'credentials/w3c.md'
    - Trust Framework:
      - Overview: 'trustframework/tf-overview.md'
      - Smart Contracts: 'trustframework/smart-contracts.md'
    - DID Methods:
      - ELSI: 'didmethods/elsi.md'
    - Interoperability:
      - with EUDCC: 'interoperability/interoperability-eudcc.md'
      - with W3C: 'interoperability/interoperability-w3c.md'