@startuml SafeIsland_CredentialIssuance

autonumber
skinparam sequenceArrowThickness 3
skinparam roundcorner 10
skinparam maxmessagesize 300

box "Issuer" #f1f9ff
  actor "Operator" as OP
  database "Issuer\nbackend" as IS
end box

box "Citizen" #f1f9ff
  actor "Citizen\nwith\nmobile" as CI
end box

box "Trust Framework" #f1f9ff
  participant "Universal\nResolver" as UR
end box

== Credential generation ==
OP -> IS: Start generation of credential
IS -> IS: Obtain credential data from KYC
IS -> IS: Generate & Save Credential
OP -> IS: Display Credential QR

== Citizen receives Credential ==
CI -> CI: Opens QR scanner
IS -[#0000FF]-> CI: Scan Credential QR
note right: QR contains URL\nto obtain Credential data
CI -> IS: Request full Credential
activate IS
return Receive Credential data

== Verification of Credential ==
CI -> CI: Verify Credential
CI -> UR: Verify signature of Credential
CI -> CI: Save Credential


@enduml

